[build-system]
requires = ["setuptools", "setuptools-scm", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/fmu/sumo/uploader/version.py"

[tool.isort]
profile = "black"

[tool.black]
line-length = 79

[project]
name = "fmu-sumo-uploader"
description = "A Python library for uploading files to Azure using sumo"
readme = { file = "README.md", content-type = "text/markdown", charset = "UTF-8" }
authors = [{ name = "Equinor", email = "dbs@equinor.com" }]
license = { file = "LICENSE" }
requires-python = ">=3.8"
dynamic = ["version"]
classifiers = [
    "Development Status :: 5 - Development/Experimental",
    "Environment :: Console",
    "Environment :: MacOS X",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    # Topic :: Scientific/Engineering :: Bio-Informatics
]
dependencies = [
    "sumo-wrapper-python",
    "pandas",
    "azure-core",
    "fmu-dataio",
    "urllib3<2.0",
    "openvds; sys_platform != 'darwin'",
]

[project.urls]
Source = "https://github.com/equinor/fmu-sumo-uploader"
Tracker = "https://github.com/equinor/fmu-sumo-uploader/issues"

[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools]
package-dir = { "" = "src" }
include-package-data = true
platforms = ["any"]


[tool.setuptools.packages.find]
where = ["src"]

[bdist_wheel]
universal = 1

[aliases]
test = "pytest"

[project.scripts]
sumo_upload = "fmu.sumo.uploader.scripts.sumo_upload:main"

[project.entry-points.ert]
fmu_sumo_jobs = "fmu.sumo.hook_implementations.jobs"
sumo_upload = "fmu.sumo.uploader.scripts.sumo_upload"
